export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const ERROR_WHILE_FETCHING_PROFILE = 'ERROR_WHILE_FETCHING_PROFILE';

export const REQUEST_NOTES = 'REQUEST_NOTES';
export const RECEIVE_NOTES = 'RECEIVE_NOTES';
export const ADD_NOTE = 'ADD_NOTE';
